language: ruby
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
rvm:
  - 1.9.3-p484
  - 2.0.0
  - 2.1.7
  - ruby-head
env:
  - PUPPET_GEM_VERSION="> 4.0.0"
  - PUPPET_GEM_VERSION="4.3.1"
  - PUPPET_GEM_VERSION="< 4.0.0"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="< 4.0.0"
notifications:
  email: true
